name = "ai-fitness-buddy"
# 将 Cloudflare Pages 的构建产物指向 public 目录（本项目为静态站点 + Pages Functions）
pages_build_output_dir = "./public"
compatibility_date = "2024-10-01"

# 可在 Cloudflare Dashboard 的 Pages -> Settings -> Environment variables 中设置同名变量
# 或者使用 wrangler.toml 的 [vars] / [env.production.vars] 进行设置（建议在 Dashboard 设置，避免把敏感信息写入仓库）
# [vars]
# ANALYZE_API_URL = "https://your-python-service.example.com/api/analyze"
